export const EditorCy = 'editor_cy'
export const ButtonSubmitSpecificationCy = 'button_submit_specification_cy'
export const TextareaSpecificationCy = 'textarea_specification_cy'
export const TitleSpecificationCy = 'title_specification_cy'
export const PopUpSpecificationCy = 'pop_up_specification_cy'