export const ModalContentStyle = {
	position: 'absolute',
	top: '50%',
	left: '50%',
	transform: 'translate(-50%, -50%)',
	minWidth: '400px',
	maxWidth: '1000px',
	minHeight: '500px',
	backgroundColor: 'white',
	padding: '75px',
	borderRadius: '10px',
	display: 'flex',
	flexDirection: 'column',
	alignItems: 'center',
}